#! /bin/sh -e
mkdir -p "build"
mkdir -p "generated"
mkdir -p "bootstrap/build"
mkdir -p "bootstrap/generated"
(bison -b "./bootstrap/generated/parser" "src/parser.yy")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarDriver.cpp.data" "templates/ArgGrammarDriver.cpp")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarDriver.hpp.data" "templates/ArgGrammarDriver.hpp")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarParser.yy.data" "templates/ArgGrammarParser.yy")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarScanner.cpp.data" "templates/ArgGrammarScanner.cpp")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarScanner.hpp.data" "templates/ArgGrammarScanner.hpp")
(ld --relocatable --format=binary --output="./bootstrap/generated/template-ArgGrammarScanner.ll.data" "templates/ArgGrammarScanner.ll")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarDriver.cpp.data" "./bootstrap/build/template-ArgGrammarDriver.cpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarDriver.hpp.data" "./bootstrap/build/template-ArgGrammarDriver.hpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarParser.yy.data" "./bootstrap/build/template-ArgGrammarParser.yy.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarScanner.cpp.data" "./bootstrap/build/template-ArgGrammarScanner.cpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarScanner.hpp.data" "./bootstrap/build/template-ArgGrammarScanner.hpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "./bootstrap/generated/template-ArgGrammarScanner.ll.data" "./bootstrap/build/template-ArgGrammarScanner.ll.o")
(bison -b "generated/parser" "src/parser.yy")
(flex -o "./bootstrap/generated/lexer.ll.cc" "src/lexer.ll")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/semantic-checking.cpp" -o "./bootstrap/build/semantic-checking.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/pretty-printer.cpp" -o "./bootstrap/build/pretty-printer.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/parse-tree.cpp" -o "./bootstrap/build/parse-tree.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/main.cpp" -o "./bootstrap/build/main.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/driver.cpp" -o "./bootstrap/build/driver.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "src/debugJSON.cpp" -o "./bootstrap/build/debugJSON.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "./bootstrap/generated/parser.tab.cc" -o "./bootstrap/build/parser.tab.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -I "src" -I "./bootstrap/generated" -c "./bootstrap/generated/lexer.ll.cc" -o "./bootstrap/build/lexer.ll.o")
(clang++ ./bootstrap/build/template-ArgGrammarDriver.cpp.o ./bootstrap/build/template-ArgGrammarDriver.hpp.o ./bootstrap/build/template-ArgGrammarParser.yy.o ./bootstrap/build/template-ArgGrammarScanner.cpp.o ./bootstrap/build/template-ArgGrammarScanner.hpp.o ./bootstrap/build/template-ArgGrammarScanner.ll.o ./bootstrap/build/lexer.ll.o ./bootstrap/build/parser.tab.o ./bootstrap/build/debugJSON.o ./bootstrap/build/driver.o ./bootstrap/build/main.o ./bootstrap/build/parse-tree.o ./bootstrap/build/pretty-printer.o ./bootstrap/build/semantic-checking.o  -lmstch -lstdc++fs -o "./bootstrap/fcap")
(cd ./bootstrap && ./fcap ../fcap.argspec)
(cd generated && bison ".././bootstrap/fcapArgGrammarParser.yy")
(cd generated && flex -o "generated/fcapArgGrammarScanner.ll.cc" ".././bootstrap/fcapArgGrammarScanner.ll")
(flex -o "generated/lexer.yy.cc" "src/lexer.ll")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarDriver.cpp.data" "templates/ArgGrammarDriver.cpp")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarDriver.hpp.data" "templates/ArgGrammarDriver.hpp")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarParser.yy.data" "templates/ArgGrammarParser.yy")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarScanner.cpp.data" "templates/ArgGrammarScanner.cpp")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarScanner.hpp.data" "templates/ArgGrammarScanner.hpp")
(ld --relocatable --format=binary --output="generated/template-ArgGrammarScanner.ll.data" "templates/ArgGrammarScanner.ll")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarDriver.cpp.data" "build/template-ArgGrammarDriver.cpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarDriver.hpp.data" "build/template-ArgGrammarDriver.hpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarParser.yy.data" "build/template-ArgGrammarParser.yy.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarScanner.cpp.data" "build/template-ArgGrammarScanner.cpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarScanner.hpp.data" "build/template-ArgGrammarScanner.hpp.o")
(objcopy --rename-section .data=.rodata,alloc,load,readonly,data,contents "generated/template-ArgGrammarScanner.ll.data" "build/template-ArgGrammarScanner.ll.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "generated/fcapArgGrammarParser.tab.cc" -o "build/fcapArgGrammarParser.tab.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "generated/fcapArgGrammarScanner.ll.cc" -o "build/fcapArgGrammarScanner.ll.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "generated/lexer.yy.cc" -o "build/lexer.yy.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "generated/parser.tab.cc" -o "build/parser.tab.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/debugJSON.cpp" -o "build/debugJSON.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/driver.cpp" -o "build/driver.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/main.cpp" -o "build/main.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/parse-tree.cpp" -o "build/parse-tree.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/pretty-printer.cpp" -o "build/pretty-printer.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "src/semantic-checking.cpp" -o "build/semantic-checking.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "./bootstrap/fcapArgGrammarDriver.cpp" -o "build/fcapArgGrammarDriver.o")
(clang++  -pedantic -std=c++17 -Wall -Wno-unused-parameter -Wno-reorder -Wno-sign-compare -Wno-address -Wno-noexcept-type -Wno-unknown-attributes -Wno-unknown-warning-option -DCOMMANDLINE_INTERFACE -I "src" -I "generated" -I "./bootstrap" -c "./bootstrap/fcapArgGrammarScanner.cpp" -o "build/fcapArgGrammarScanner.o")
(clang++ build/template-ArgGrammarDriver.cpp.o build/template-ArgGrammarDriver.hpp.o build/template-ArgGrammarParser.yy.o build/template-ArgGrammarScanner.cpp.o build/template-ArgGrammarScanner.hpp.o build/template-ArgGrammarScanner.ll.o build/fcapArgGrammarParser.tab.o build/fcapArgGrammarScanner.ll.o build/lexer.yy.o build/parser.tab.o build/debugJSON.o build/driver.o build/main.o build/parse-tree.o build/pretty-printer.o build/semantic-checking.o build/fcapArgGrammarDriver.o build/fcapArgGrammarScanner.o  -lmstch -lstdc++fs -o "fcap")
